---

version: '2'
services:
  jenkins-master:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "jenkins_home:/var/jenkins_home"
    environment:
      - "JAVA_OPTS=-Djenkins.install.runSetupWizard=false"
      - "JENKINS_USER=admin"
      - "JENKINS_PASS=admin"

volumes:
  jenkins_home:
