---

jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: nimda
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
unclassified:
  location:
    adminAddress: "you@example.com"
    url: "http://192.168.30.38:8080/"
security:
  scriptApproval:
    approvedSignatures:
      - "method hudson.model.Actionable getAction java.lang.Class"
      - "method hudson.model.ParametersAction getParameters"
      - "method java.util.concurrent.Semaphore acquire"
      - "method java.util.concurrent.Semaphore release"
      - "method java.util.concurrent.locks.Lock lock"
      - "method java.util.concurrent.locks.Lock unlock"
      - "new java.util.concurrent.Semaphore int"
      - "new java.util.concurrent.locks.ReentrantLock"
      - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods next java.lang.String"
