- job:
    name: "build"
    description: "build"
    defaults: global
    scm:
      - tf-jenkins
      - tf-dev-env
    parameters:
      - label:
          name: SLAVE
    builders:
      - shell: |
          export ENVIRONMENT_OS=centos7
          ./src/progmaticlab/tf-jenkins/jobs/build/create_workers.sh
      - shell: |
          # TODO: pass nexus creds
          ./src/progmaticlab/tf-jenkins/jobs/build/run.sh
