---
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
  jenkins-master:
    image: jenkins/jenkins:lts
    container_name: nginx-master
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    network_mode: bridge
    environment:
      - "VIRTUAL_HOST=tf-jenkins.progmaticlab.com"
      - "VIRTUAL_PORT=8080"
      - "LETSENCRYPT_HOST=tf-jenkins.progmaticlab.com"
      - "LETSENCRYPT_EMAIL=null@progmaticlab.com"
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  jenkins_home:
