---

# jobs are divided into two parts:
# - jobs that are run as is: build, test-unit, test-lint. These jobs depend only on fetch-sources
# job that is automatically added into pipeline is any of these jobs present.
# - jobs that are treated as test configurations and translated into several jobs:
# deploy platform, deploy TF, run sanity/smoke, ... sanity is enabed by default and smoke is disabled

- project-template:
    name: unittests
    check:
      jobs:
        - test-unit

- project-template:
    name: unittests-webui
    check:
      jobs:
        - test-unit:
            vars:
              TARGET: ui

- project-template:
    name: systests
    check:
      jobs:
        - build
        - k8s_manifests:
            voting: false
            smoke: true
        - ansible_k8s
        - ansible_os

- project:
    name: Juniper/contrail-container-builder
    templates:
      - systests
    experimental:
      jobs:
        - build:
            vars:
              CONTRAIL_BUILD_FROM_SOURCE: true
              SECOND_TEST_PARAM: "This is string"
        - k8s_manifests:
            voting: false
            smoke: true

- project:
    name: Juniper/contrail-controller
    templates:
      - unittests
      - systests

- project:
    name: Juniper/contrail-helm-deployer
    templates:
      - unittests
      - systests
    check:
      jobs:
        - helm_os:
            voting: false

- project:
    name: Juniper/contrail-third-party-packages
    templates:
      - unittests
      - systests

- project:
    name: Juniper/contrail-web-core
    templates:
      - unittests-webui

- project:
    name: Juniper/contrail-web-controller
    templates:
      - unittests-webui

- project:
    name: Juniper/contrail-webui-third-party
    templates:
      - unittests-webui
