---

- project-template:
    name: unittests
    check:
      jobs:
        - test-unit

- project-template:
    name: unittests-webui
    check:
      jobs:
        - test-unit:
            vars:
              TARGET: webui

- project-template:
    name: systests
    check:
      jobs:
        - build
        - k8s_manifests
        - ansible_k8s
        - ansible_os

- project:
    name: Juniper/contrail-container-builder
    templates:
      - systests
    experimental:
      jobs:
        - build:
            vars:
              CONTRAIL_BUILD_FROM_SOURCE: true

- project:
    name: Juniper/contrail-controller
    templates:
      - unittests
      - systests

- project:
    name: Juniper/contrail-helm-deployer
    templates:
      - unittests
      - systests
    check:
      jobs:
        - helm_os:
            voting: false

- project:
    name: Juniper/contrail-web-core
    templates:
      - unittests-webui

- project:
    name: Juniper/contrail-web-controller
    templates:
      - unittests-webui

- project:
    name: Juniper/contrail-webui-third-party
    templates:
      - unittests-webui
