---

- include:
    - templates.yaml

- project:
    name: tungstenfabric
    nightly:
      templates:
        - test-unit
        - test-unit-ui
        - k8s-manifests
        - ansible-k8s
        - ansible-os
        - cleanup
      jobs:
        publish-centos-nightly:
          job-name: publish
          depends-on:
            - build-centos
      post-jobs:
        publish-centos-stable:
          job-name: publish

- project:
    name: Juniper/contrail-ansible-deployer
    check:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: Juniper/contrail-deployers-containers
    check:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - ansible-k8s
        - ansible-os
        - cleanup

- project:
    name: Juniper/contrail-container-builder
    check:
      templates:
        - k8s-manifests
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - build-centos
        - cleanup
    experimental:
      templates:
        - ansible-os
        - cleanup
      jobs:
        build-centos:
          job-name: build
          depends-on:
            - fetch-sources-centos
          vars:
            CONTRAIL_BUILD_FROM_SOURCE: true

- project:
    name: Juniper/contrail-controller
    check:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup
    gate:
      templates:
        - test-unit
        - ansible-k8s
        - ansible-os
        - cleanup
