---

# jobs are divided into two parts:
# jobs that are run as is: fetch-sources, build, test-unit, test-lint.
# jobs that are treated as test configurations and translated into several jobs:
#   deploy platform, deploy TF, run sanity/smoke, ... sanity is enabed by default and smoke is disabled

# Example of jobs definition
#jobs:
#  - fetch-sources-centos:
#      job-name: fetch-sources
#  - build-centos:
#      job-name: build
#  - test-unit
#  - test-unit-ui:
#      job-name: test-unit
#      vars:
#        TARGET: ui
#  - ansible_k8s
#      wait-for-build-job: build-centos
#      voting: true
#      smoke: false
#      sanity: true


- project-template:
    name: unittests
    check:
      jobs:
        - fetch-sources
        - test-unit

- project-template:
    name: unittests-webui
    check:
      jobs:
        - fetch-sources
        - test-unit:
            vars:
              TARGET: ui

- project-template:
    name: systests
    check:
      jobs:
        - fetch-sources
        - build
        - k8s_manifests:
            voting: false
            smoke: true
        - ansible_k8s
        - ansible_os

- project:
    name: tungstenfabric
    nightly:
      jobs:
        - fetch-sources
        - build
        - test-unit
        - ansible_k8s
        - ansible_os
        - helm_k8s
        - helm_os
        - k8s_manifests:
            voting: false
            smoke: true
        - juju_k8s:
            voting: false
            smoke: true
        - juju_os:
            voting: false
            smoke: true
        # TODO: think how to choose image tag (centos/rhel) for sanity jobs 
        #- fetch-sources-rhel:
        #    job-name: fetch-sources
        #    vars:
        #      ENVIRONMENT_OS: rhel7
        #- build-rhel:
        #    job-name: build
        #    vars:
        #      ENVIRONMENT_OS: rhel7

- project:
    name: Juniper/contrail-container-builder
    templates:
      - systests
    experimental:
      jobs:
        - fetch-sources
        - build:
            vars:
              CONTRAIL_BUILD_FROM_SOURCE: true
        - ansible_os:
            smoke: true

- project:
    name: Juniper/openshift-ansible
    branches:
      - ^release-3\.[0-9]+-contrail$
    check:
      jobs:
        - fetch-sources:
            vars:
              ENVIRONMENT_OS: rhel7
        - build:
            vars:
              ENVIRONMENT_OS: rhel7
        - k8s_manifests:
            voting: false
            sanity: false
            smoke: true

- project:
    name: Juniper/contrail-controller
    templates:
      - unittests
      - systests

- project:
    name: Juniper/contrail-common
    templates:
      - unittests
      - systests

- project:
    name: Juniper/contrail-api-client
    templates:
      - unittests
      - systests

- project:
    name: Juniper/contrail-vrouter
    templates:
      - unittests
      - systests

- project:
    name: tungstenfabric/tf-analytics
    templates:
      - unittests
      - systests

- project:
    name: Juniper/contrail-helm-deployer
    templates:
      - systests
    check:
      jobs:
        - helm_k8s
        - helm_os

- project:
    name: Juniper/contrail-third-party-packages
    templates:
      - unittests
      - systests

- project:
    name: tungstenfabric/tf-charms
    check:
      jobs:
        - juju_k8s:
            voting: false
            smoke: true
        - juju_os:
            voting: false
            smoke: true

- project:
    name: Juniper/contrail-web-core
    templates:
      - unittests-webui

- project:
    name: Juniper/contrail-web-controller
    templates:
      - unittests-webui

- project:
    name: Juniper/contrail-webui-third-party
    templates:
      - unittests-webui

- project:
    name: Juniper/contrail-tripleo-heat-templates
    check:
      jobs:
        - rhosp

- project:
    name: tungstenfabric/tf-helm-deployer
    templates:
      - systests
    check:
      jobs:
        - helm_os
        - helm_k8s

- project:
    name: tungstenfabric/tf-devstack
    templates:
      - systests
