---

- project:
    name: Juniper/openshift-ansible
    branches:
      - ^release-3\.[0-9]+-contrail$
    # TODO: implentation openshift deployment jobs
    # check:
    #   jobs:
    #     - fetch-sources:
    #         vars:
    #           ENVIRONMENT_OS: rhel7
    #     - build:
    #         vars:
    #           ENVIRONMENT_OS: rhel7
    #     - openshift:
    #         voting: false
    #         sanity: false
    #         smoke: true
    # gate:
    #   jobs:
    #     - fetch-sources:
    #         vars:
    #           ENVIRONMENT_OS: rhel7
    #     - build:
    #         vars:
    #           ENVIRONMENT_OS: rhel7
    #     - openshift:
    #         voting: false
    #         sanity: false
    #         smoke: true

- project:
    name: Juniper/contrail-tripleo-heat-templates
    check:
      jobs:
        - rhosp
    gate:
      jobs:
        - rhosp

- project:
    name: tungstenfabric/tf-helm-deployer
    templates:
      - systests
    check:
      jobs:
        - helm_os
        - helm_k8s
    gate:
      jobs:
        - helm_os
        - helm_k8s

- project:
    name: tungstenfabric/tf-devstack
    templates:
      - systests
