---

- template:
    name: cleanup
    post-jobs:
      cleanup-pipeline-workers:

- template:
    name: fetch-sources-centos
    jobs:
      fetch-sources-centos:
        job-name: fetch-sources

- template:
    name: build-centos
    parents:
      - fetch-sources-centos
    jobs:
      build-centos:
        job-name: build
        depends-on:
          - fetch-sources-centos
      
- template:
    name: test-unit
    parents:
      - fetch-sources-centos
    jobs:
      test-unit:
        depends-on:
          - fetch-sources-centos

- template:
    name: test-unit-ui
    parents:
      - fetch-sources-centos
    jobs:
      test-unit-ui:
        job-name: test-unit
        depends-on:
          - fetch-sources-centos
        vars:
          TARGET: ui

- template:
    name: k8s-manifests
    parents:
      - build-centos
    streams:
      k8s-manifests:
        voting: false
    jobs:
      deploy-platform-k8s-manifests:
        stream: k8s-manifests
      deploy-tf-k8s-manifests:
        stream: k8s-manifests
        depends-on:
          - build-centos
          - deploy-platform-k8s-manifests
      test-sanity-k8s-manifests:
        job-name: test-sanity
        stream: k8s-manifests
        depends-on:
          - deploy-tf-k8s-manifests
      test-smoke-k8s-manifests:
        job-name: test-smoke
        stream: k8s-manifests
        depends-on:
          - deploy-tf-k8s-manifests
      collect-logs-and-cleanup-k8s-manifests:
        job-name: collect-logs-and-cleanup
        stream: k8s-manifests
        force-run: true
        depends-on:
          - deploy-platform-k8s-manifests
          - deploy-tf-k8s-manifests
          - test-sanity-k8s-manifests
          - test-smoke-k8s-manifests

- template:
    name: ansible-k8s
    parents:
      - build-centos
    streams:
      ansible-k8s:
    jobs:
      deploy-platform-ansible-k8s:
        stream: ansible-k8s
        depends-on:
          # temporary solution while we don't have container with ansible-deployer before build
          - build-centos
      deploy-tf-ansible-k8s:
        stream: ansible-k8s
        depends-on:
          - deploy-platform-ansible-k8s
      test-sanity-ansible-k8s:
        job-name: test-sanity
        stream: ansible-k8s
        depends-on:
          - deploy-tf-ansible-k8s
      collect-logs-and-cleanup-ansible-k8s:
        job-name: collect-logs-and-cleanup
        stream: ansible-k8s
        force-run: true
        depends-on:
          - deploy-platform-ansible-k8s
          - deploy-tf-ansible-k8s
          - test-sanity-ansible-k8s

- template:
    name: ansible-os
    parents:
      - build-centos
    streams:
      ansible-os:
    jobs:
      deploy-platform-ansible-os:
        stream: ansible-os
        depends-on:
          # temporary solution while we don't have container with ansible-deployer before build
          - build-centos
      deploy-tf-ansible-os:
        stream: ansible-os
        depends-on:
          - deploy-platform-ansible-os
      test-sanity-ansible-os:
        job-name: test-sanity
        stream: ansible-os
        depends-on:
          - deploy-tf-ansible-os
      collect-logs-and-cleanup-ansible-os:
        job-name: collect-logs-and-cleanup
        stream: ansible-os
        force-run: true
        depends-on:
          - deploy-platform-ansible-os
          - deploy-tf-ansible-os
          - test-sanity-ansible-os

- template:
    name: helm-k8s
    parents:
      - build-centos
    streams:
      helm-k8s:
    jobs:
      deploy-platform-helm-k8s:
        stream: helm-k8s
      deploy-tf-helm-k8s:
        stream: helm-k8s
        depends-on:
          - build-centos
          - deploy-platform-helm-k8s
      test-sanity-helm-k8s:
        job-name: test-sanity
        stream: helm-k8s
        depends-on:
          - deploy-tf-helm-k8s
      collect-logs-and-cleanup-helm-k8s:
        job-name: collect-logs-and-cleanup
        stream: helm-k8s
        force-run: true
        depends-on:
          - deploy-platform-helm-k8s
          - deploy-tf-helm-k8s
          - test-sanity-helm-k8s

- template:
    name: helm-os
    parents:
      - build-centos
    streams:
      helm-os:
    jobs:
      deploy-platform-helm-os:
        stream: helm-os
      deploy-tf-helm-os:
        stream: helm-os
        depends-on:
          - build-centos
          - deploy-platform-helm-os
      test-sanity-helm-os:
        job-name: test-sanity
        stream: helm-os
        depends-on:
          - deploy-tf-helm-os
      collect-logs-and-cleanup-helm-os:
        job-name: collect-logs-and-cleanup
        stream: helm-os
        force-run: true
        depends-on:
          - deploy-platform-helm-os
          - deploy-tf-helm-os
          - test-sanity-helm-os

- template:
    name: juju-k8s
    parents:
      - build-centos
    streams:
      juju-k8s:
    jobs:
      deploy-platform-juju-k8s:
        stream: juju-k8s
      deploy-tf-juju-k8s:
        stream: juju-k8s
        depends-on:
          - build-centos
          - deploy-platform-juju-k8s
      test-sanity-juju-k8s:
        job-name: test-sanity
        stream: juju-k8s
        depends-on:
          - deploy-tf-juju-k8s
      collect-logs-and-cleanup-juju-k8s:
        job-name: collect-logs-and-cleanup
        stream: juju-k8s
        force-run: true
        depends-on:
          - deploy-platform-juju-k8s
          - deploy-tf-juju-k8s
          - test-sanity-juju-k8s

- template:
    name: juju-os
    parents:
      - build-centos
    streams:
      juju-os:
    jobs:
      deploy-platform-juju-os:
        stream: juju-os
      deploy-tf-juju-os:
        stream: juju-os
        depends-on:
          - build-centos
          - deploy-platform-juju-os
      test-sanity-juju-os:
        job-name: test-sanity
        stream: juju-os
        depends-on:
          - deploy-tf-juju-os
      collect-logs-and-cleanup-juju-os:
        job-name: collect-logs-and-cleanup
        stream: juju-os
        force-run: true
        depends-on:
          - deploy-platform-juju-os
          - deploy-tf-juju-os
          - test-sanity-juju-os
