required_pkgs:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3
    - python3-dev
    - python3-pip
    - python3-setuptools
    - python3-venv

jenkins_fqdn: "fp.progmaticlab.com"
jenkins_admin_email: "null@progmaticlab.com"
jenkins_custom_docker_image: true
jenkins_install_plugins: true
jenkins_deploy_configuration: true
