---
all:
  hosts:
    jenkins1:
      ansible_host: 192.168.30.205
      ansible_user: ubuntu
  children:
    jenkins-master:
      hosts:
        jenkins1
    py3-hosts:
      hosts:
        jenkins1
